import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  // Only seed if tables are empty — never delete existing data
  const productCount = await prisma.product.count();
  const userCount = await prisma.user.count();
  if (productCount > 0 && userCount > 0) {
    console.log("⚠️  Database already has data — skipping seed (use fix-products.ts to reset products)");
    console.log(`   Products: ${productCount}, Users: ${userCount}`);
    return;
  }

  // Seed admin user (upsert to handle existing)
  const adminPassword = await bcrypt.hash("admin123", 12);
  await prisma.user.upsert({
    where: { phone: "09120000000" },
    update: {},
    create: {
      id: "admin-001",
      username: "admin",
      phone: "09120000000",
      passwordHash: adminPassword,
      role: "admin",
      status: "active",
      walletBalance: 0,
    },
  });

  // Seed demo user (upsert to handle existing)
  const userPassword = await bcrypt.hash("user123", 12);
  await prisma.user.upsert({
    where: { phone: "09375302400" },
    update: {},
    create: {
      id: "user-001",
      username: "demo_user",
      phone: "09375302400",
      passwordHash: userPassword,
      role: "user",
      status: "active",
      walletBalance: 150,
    },
  });

  // Seed products
  // Pricing model: daily = price×0.35, weekly = price×0.70, monthly = price, lifetime = price×2.50
  const products = [
    {
      id: "g1_aim",
      name: "Aegis Codex Aimbot",
      slug: "aegis-codex-aimbot",
      game: "Dota 2",
      category: "Aimbot",
      price: 24.99,
      priceDaily: 8.75,
      priceWeekly: 17.49,
      priceMonthly: 24.99,
      priceLifetime: 62.48,
      rating: 4.9,
      reviewsCount: 142,
      features: JSON.stringify(["Dynamic skill-shot tracking", "Automated last-hit & raw lane management", "Humanized linear delays", "Safe memory overlay technology"]),
      description: "Ultra-precise dynamic prediction aimbot optimized for target skill-shots, automated creep-denial, and continuous map safety.",
      isPopular: true,
      bypassRate: "99.9%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/aegis-codex-aimbot.svg",
      bannerImage: "/images/products/aegis-codex-aimbot.svg",
      metaTitle: "Aegis Codex Aimbot for Dota 2 — Undetectable",
      metaTitleFa: "ایم‌بات آجیس کدکس برای Dota 2 — غیرقابل شناسایی",
      metaDescription: "Get the best Aegis Codex aimbot for Dota 2. Dynamic skill-shot tracking, auto last-hit, humanized delays. 99.9% undetected. Buy now!",
      metaDescriptionFa: "بهترین ایم‌بات آجیس کدکس برای Dota 2. ردیابی داینامیک شات، لاست‌هیت خودکار، تأخیر انسانی. ۹۹.۹٪ غیرقابل شناسایی.",
      focusKeyphrase: "dota 2 aimbot",
      focusKeyphraseFa: "ایم‌بات dota 2",
      metaKeywords: JSON.stringify(["dota 2 aimbot", "dota 2 cheat", "aegis codex", "best dota 2 hack", "dota aim assist", "undetected dota 2"]),
      metaKeywordsFa: JSON.stringify(["ایم‌بات dota 2", "چیت dota 2", "آجیس کدکس", "بهترین هک dota", "کمک ایم dota"]),
      ogTitle: "Aegis Codex Aimbot — #1 Dota 2 Aimbot",
      ogDescription: "Dominate Dota 2 with the most undetectable aimbot. Dynamic tracking, auto last-hit, and safe overlay technology.",
      twitterTitle: "Aegis Codex Aimbot for Dota 2",
      twitterDescription: "The most advanced undetected aimbot for Dota 2. Get yours now!",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g1_esp",
      name: "Oracle Vision ESP",
      slug: "oracle-vision-esp",
      game: "Dota 2",
      category: "ESP Overlay",
      price: 19.99,
      priceDaily: 7.00,
      priceWeekly: 13.99,
      priceMonthly: 19.99,
      priceLifetime: 49.98,
      rating: 4.8,
      reviewsCount: 98,
      features: JSON.stringify(["Total fog-of-war transparency", "Neutral camp cooldown countdowns", "Dynamic danger boundary warnings", "Warranted ward-placement radar"]),
      description: "Gain complete battlefield transparency with detailed dynamic indicators showcasing camp cooldowns, enemy structures, and fog wards.",
      isPopular: false,
      bypassRate: "99.7%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/oracle-vision-esp.svg",
      bannerImage: "/images/products/oracle-vision-esp.svg",
      metaTitle: "Oracle Vision ESP for Dota 2 — Full Map Hack",
      metaTitleFa: "اورکل ویژن ESP برای Dota 2 — هک کامل نقشه",
      metaDescription: "Oracle Vision ESP gives complete battlefield transparency for Dota 2. Camp cooldowns, fog wards, danger warnings. Undetected.",
      metaDescriptionFa: "اورکل ویژن ESP شفافیت کامل میدان نبرد برای Dota 2. کولدان کمپ، واردهای مه، هشدار خطر. غیرقابل شناسایی.",
      focusKeyphrase: "dota 2 esp hack",
      focusKeyphraseFa: "هک esp dota 2",
      metaKeywords: JSON.stringify(["dota 2 esp", "dota 2 wallhack", "oracle vision", "dota map hack", "dota 2 vision hack"]),
      metaKeywordsFa: JSON.stringify(["esp dota 2", "وال‌هک dota 2", "اورکل ویژن", "هک نقشه dota"]),
      ogTitle: "Oracle Vision ESP — See Everything in Dota 2",
      ogDescription: "Complete battlefield transparency with camp cooldowns, fog wards, and danger warnings for Dota 2.",
      twitterTitle: "Oracle Vision ESP for Dota 2",
      twitterDescription: "See everything through walls. The ultimate ESP for Dota 2.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g2_aim",
      name: "Cyber-Sentry Engine",
      slug: "cyber-sentry-engine",
      game: "R6 Siege",
      category: "Aimbot",
      price: 34.99,
      priceDaily: 12.25,
      priceWeekly: 24.49,
      priceMonthly: 34.99,
      priceLifetime: 87.48,
      rating: 4.95,
      reviewsCount: 215,
      features: JSON.stringify(["Micro-recoil elimination vector", "Wall-penetration bullet predictor", "Smart-bone targeting (Head/Neck/Chest)", "Zero overlay flicker on capture"]),
      description: "An elite recoil stabilizer and adaptive silent-aim core calibrated for structural frame breaches and pixel-perfect tactical executions.",
      isPopular: true,
      bypassRate: "99.95%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/cyber-sentry-engine.svg",
      bannerImage: "/images/products/cyber-sentry-engine.svg",
      metaTitle: "Cyber-Sentry Engine — R6 Siege Aimbot | Undetected",
      metaTitleFa: "موتور سایبر-سنتری — ایم‌بات R6 Siege | غیرقابل شناسایی",
      metaDescription: "Elite Cyber-Sentry aimbot for R6 Siege. Micro-recoil elimination, wall-penetration predictor, smart-bone targeting. 99.95% undetected.",
      metaDescriptionFa: "ایم‌بات حرفه‌ای سایبر-سنتری برای R6 Siege. حذف ریکول، پیش‌بین نفوذ دیوار، تارگت اسکلتی. ۹۹.۹۵٪ غیرقابل شناسایی.",
      focusKeyphrase: "r6 siege aimbot",
      focusKeyphraseFa: "ایم‌بات r6 siege",
      metaKeywords: JSON.stringify(["r6 siege aimbot", "rainbow six cheat", "cyber sentry", "r6s hack", "siege aim assist", "undetected r6"]),
      metaKeywordsFa: JSON.stringify(["ایم‌بات r6", "چیت rainbow six", "سایبر سنتری", "هک r6s"]),
      ogTitle: "Cyber-Sentry Engine — Best R6 Siege Aimbot",
      ogDescription: "Precision recoil stabilizer and silent-aim core for Rainbow Six Siege. Pixel-perfect tactical executions.",
      twitterTitle: "Cyber-Sentry Engine for R6 Siege",
      twitterDescription: "The elite aimbot for R6 Siege. Recoil elimination and wall-penetration prediction.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g2_esp",
      name: "Valkyrie Structural Radar",
      slug: "valkyrie-structural-radar",
      game: "R6 Siege",
      category: "ESP Overlay",
      price: 29.99,
      priceDaily: 10.50,
      priceWeekly: 20.99,
      priceMonthly: 29.99,
      priceLifetime: 74.98,
      rating: 4.7,
      reviewsCount: 88,
      features: JSON.stringify(["Full skeletal bone glow rendering", "Gadgets & electronics tracker", "Accurate health & fuel metrics", "Behind-barrier 3D box framing"]),
      description: "Complete wall visibility and real-time operator bone outlines, showcasing gadget locations, health, and equipment tiers.",
      isPopular: false,
      bypassRate: "99.6%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/valkyrie-structural-radar.svg",
      bannerImage: "/images/products/valkyrie-structural-radar.svg",
      metaTitle: "Valkyrie Structural Radar — R6 Siege ESP Overlay",
      metaTitleFa: "رادار ساختاری والکایر — ESP روی R6 Siege",
      metaDescription: "Full skeletal ESP and wall visibility for R6 Siege. Operator bone outlines, gadget tracking, health metrics. Undetected.",
      metaDescriptionFa: "ESP اسکلتی کامل و دید دیوار برای R6 Siege. خطوط اسکلت اپراتور، ردیاب گجت، متریک سلامت. غیرقابل شناسایی.",
      focusKeyphrase: "r6 siege esp",
      focusKeyphraseFa: "esp r6 siege",
      metaKeywords: JSON.stringify(["r6 siege esp", "valkyrie radar", "siege wallhack", "r6s esp overlay", "rainbow six hack"]),
      metaKeywordsFa: JSON.stringify(["esp r6", "رادار والکایر", "وال‌هک siege", "هک rainbow six"]),
      ogTitle: "Valkyrie Structural Radar — See Through Walls in R6",
      ogDescription: "Complete wall visibility with skeleton glow, gadget tracking, and health metrics for Rainbow Six Siege.",
      twitterTitle: "Valkyrie Structural Radar for R6 Siege",
      twitterDescription: "See through walls with full skeletal ESP for R6 Siege.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g3_aim",
      name: "Vanguard-Bypass Core",
      slug: "vanguard-bypass-core",
      game: "Valorant",
      category: "Aimbot",
      price: 39.99,
      priceDaily: 14.00,
      priceWeekly: 27.99,
      priceMonthly: 39.99,
      priceLifetime: 99.98,
      rating: 4.98,
      reviewsCount: 312,
      features: JSON.stringify(["Vanguard-isolated kernel driver", "Virtual HID inputs (Razer/Corsair custom payload)", "Smooth FOV adjustment curve", "Integrated secure clean stream mode"]),
      description: "A ring-0 kernel-mode software enhancement suite employing mouse driver virtualization and safe dynamic memory injections to bypass advanced scans.",
      isPopular: true,
      bypassRate: "99.99%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/vanguard-bypass-core.svg",
      bannerImage: "/images/products/vanguard-bypass-core.svg",
      metaTitle: "Vanguard-Bypass Core — Valorant Aimbot | Undetected",
      metaTitleFa: "هسته بایپاس وانگارد — ایم‌بات Valorant | غیرقابل شناسایی",
      metaDescription: "Premium Vanguard-bypass aimbot for Valorant. Kernel driver, virtual HID inputs, smooth FOV. 99.99% undetected. Buy now!",
      metaDescriptionFa: "ایم‌بات پریمیوم بایپاس وانگارد برای Valorant. درایور کرنل، ورودی HID مجازی، FOV نرم. ۹۹.۹۹٪ غیرقابل شناسایی.",
      focusKeyphrase: "valorant aimbot",
      focusKeyphraseFa: "ایم‌بات valorant",
      metaKeywords: JSON.stringify(["valorant aimbot", "vanguard bypass", "valorant cheat", "best valorant hack", "undetected valorant", "valorant esp"]),
      metaKeywordsFa: JSON.stringify(["ایم‌بات valorant", "بایپاس وانگارد", "چیت valorant", "بهترین هک valorant"]),
      ogTitle: "Vanguard-Bypass Core — #1 Valorant Aimbot",
      ogDescription: "Ring-0 kernel aimbot with virtual HID inputs. Bypass Vanguard anti-cheat with 99.99% success rate.",
      twitterTitle: "Vanguard-Bypass Core for Valorant",
      twitterDescription: "The most advanced undetected aimbot for Valorant. Kernel-level bypass technology.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g3_wall",
      name: "Specter Wallhack Overlay",
      slug: "specter-wallhack-overlay",
      game: "Valorant",
      category: "Wallhack",
      price: 27.99,
      priceDaily: 9.80,
      priceWeekly: 19.59,
      priceMonthly: 27.99,
      priceLifetime: 69.98,
      rating: 4.75,
      reviewsCount: 104,
      features: JSON.stringify(["Ultra-low latency outline rendering", "Bypass active screenshot scans", "Distance metrics & weapon loadout display", "Adjustable gold/cyber glow shades"]),
      description: "Render high-contrast outlines and predictive tracer vectors directly over hostile players, seamlessly bypassing screenshot validation checks.",
      isPopular: false,
      bypassRate: "99.8%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/specter-wallhack-overlay.svg",
      bannerImage: "/images/products/specter-wallhack-overlay.svg",
      metaTitle: "Specter Wallhack — Valorant Wallhack Overlay",
      metaTitleFa: "اسپکتر وال‌هک — اورلای وال‌هک Valorant",
      metaDescription: "Ultra-low latency wallhack for Valorant. High-contrast outlines, tracer vectors, bypass screenshot scans. Undetected.",
      metaDescriptionFa: "وال‌هک با تأخیر فوق‌العاده کم برای Valorant. خطوط کنتراست بالا، بردارهای تریسر، بایپاس اسکرین‌شات. غیرقابل شناسایی.",
      focusKeyphrase: "valorant wallhack",
      focusKeyphraseFa: "وال‌هک valorant",
      metaKeywords: JSON.stringify(["valorant wallhack", "specter overlay", "valorant esp", "valorant outline hack", "valorant visual hack"]),
      metaKeywordsFa: JSON.stringify(["وال‌هک valorant", "اورلای اسپکتر", "esp valorant", "هک خطوط valorant"]),
      ogTitle: "Specter Wallhack — See Enemies Through Walls",
      ogDescription: "High-contrast outlines and tracer vectors for Valorant. Bypasses screenshot validation checks.",
      twitterTitle: "Specter Wallhack for Valorant",
      twitterDescription: "See enemies through walls with ultra-low latency outline rendering.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g_spoofer",
      name: "Golden HWID Spoofer Elite",
      slug: "golden-hwid-spoofer-elite",
      game: "Valorant",
      category: "HWID Spoofer",
      price: 14.99,
      priceDaily: 5.25,
      priceWeekly: 10.49,
      priceMonthly: 14.99,
      priceLifetime: 37.48,
      rating: 4.92,
      reviewsCount: 180,
      features: JSON.stringify(["One-click registry & Disk UUID randomization", "Complete dynamic network MAC scuffing", "Shadow-ban trace file cleaner", "Supports all Intel/AMD motherboard chipsets"]),
      description: "A robust deep kernel cleaner that randomizes your disk serials, MAC addresses, motherboard registries, and NIC configurations instantly.",
      isPopular: false,
      bypassRate: "100%",
      updateStatus: "Testing",
      imageUrl: "/images/products/golden-hwid-spoofer-elite.svg",
      bannerImage: "/images/products/golden-hwid-spoofer-elite.svg",
      metaTitle: "Golden HWID Spoofer Elite — Bypass HWID Bans",
      metaTitleFa: "گلدن اسپوфер HWID الیت — بایپاس بن HWID",
      metaDescription: "Bypass any HWID ban with Golden Spoofer Elite. One-click registry, Disk UUID, MAC randomization. Supports Intel/AMD.",
      metaDescriptionFa: "بایپاس هر بن HWID با گلدن اسپوфер الیت. کلیک واحد رجیستری، Disk UUID، تصادفی MAC. پشتیبانی Intel/AMD.",
      focusKeyphrase: "hwid spoofer",
      focusKeyphraseFa: "اسپوфер hwid",
      metaKeywords: JSON.stringify(["hwid spoofer", "hwid ban bypass", "golden spoofer", "hardware spoofer", "mac spoofer", "disk uuid spoofer"]),
      metaKeywordsFa: JSON.stringify(["اسپوфер hwid", "بایپاس بن سخت‌افزاری", "اسپوфер گلدن", "تغییر مک آدرس"]),
      ogTitle: "Golden HWID Spoofer Elite — Unban Any Game",
      ogDescription: "Complete HWID ban bypass with registry, disk, and network identifier randomization. One-click solution.",
      twitterTitle: "Golden HWID Spoofer Elite",
      twitterDescription: "Bypass HWID bans instantly. Supports all major games and anti-cheat systems.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g4_aim",
      name: "Phantom Strike Aimbot",
      slug: "phantom-strike-aimbot",
      game: "CS2",
      category: "Aimbot",
      price: 29.99,
      priceDaily: 10.50,
      priceWeekly: 20.99,
      priceMonthly: 29.99,
      priceLifetime: 74.98,
      rating: 4.88,
      reviewsCount: 167,
      features: JSON.stringify(["Humanized aim smoothing", "Dynamic recoil compensation", "Adaptive FOV scaling", "Triggerbot with random delays"]),
      description: "Precision-engineered aim assistance with humanized recoil control and adaptive FOV scaling for competitive matchmaking.",
      isPopular: true,
      bypassRate: "99.85%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/phantom-strike-aimbot.svg",
      bannerImage: "/images/products/phantom-strike-aimbot.svg",
      metaTitle: "Phantom Strike Aimbot for CS2 — Undetectable",
      metaTitleFa: "ایم‌بات فانتوم استرایک برای CS2 — غیرقابل شناسایی",
      metaDescription: "Phantom Strike aimbot for CS2 with humanized smoothing, recoil compensation, adaptive FOV. 99.85% undetected. Buy now!",
      metaDescriptionFa: "ایم‌بات فانتوم استرایک برای CS2 با هموارسازی انسانی، جبران ریکول، FOV تطبیقی. ۹۹.۸۵٪ غیرقابل شناسایی.",
      focusKeyphrase: "cs2 aimbot",
      focusKeyphraseFa: "ایم‌بات cs2",
      metaKeywords: JSON.stringify(["cs2 aimbot", "phantom strike", "cs2 cheat", "csgo aimbot", "best cs2 hack", "undetected cs2"]),
      metaKeywordsFa: JSON.stringify(["ایم‌بات cs2", "فانتوم استرایک", "چیت cs2", "ایم‌بات csgo"]),
      ogTitle: "Phantom Strike — Best CS2 Aimbot",
      ogDescription: "Humanized aim assistance with recoil compensation and adaptive FOV scaling for CS2 competitive matchmaking.",
      twitterTitle: "Phantom Strike Aimbot for CS2",
      twitterDescription: "The most undetectable aimbot for CS2. Humanized smoothing and adaptive FOV.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g4_esp",
      name: "Shadow Realm ESP",
      slug: "shadow-realm-esp",
      game: "CS2",
      category: "ESP Overlay",
      price: 22.99,
      priceDaily: 8.05,
      priceWeekly: 16.09,
      priceMonthly: 22.99,
      priceLifetime: 57.48,
      rating: 4.72,
      reviewsCount: 91,
      features: JSON.stringify(["Skeleton & box ESP", "Weapon & grenade identification", "Grenade trajectory lines", "Radar hack integration"]),
      description: "Full-spectrum visual enhancement with skeleton glow, weapon identification, and grenade trajectory prediction.",
      isPopular: false,
      bypassRate: "99.7%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/shadow-realm-esp.svg",
      bannerImage: "/images/products/shadow-realm-esp.svg",
      metaTitle: "Shadow Realm ESP for CS2 — Full Visual Enhancement",
      metaTitleFa: "شادو ریلم ESP برای CS2 — تقویت بصری کامل",
      metaDescription: "Full-spectrum ESP for CS2. Skeleton glow, weapon ID, grenade trajectories, radar hack. 99.7% undetected.",
      metaDescriptionFa: "ESP طیف کامل برای CS2. درخشش اسکلت، شناسایی سلاح، مسار نارنجک، هک رادار. ۹۹.۷٪ غیرقابل شناسایی.",
      focusKeyphrase: "cs2 esp hack",
      focusKeyphraseFa: "هک esp cs2",
      metaKeywords: JSON.stringify(["cs2 esp", "shadow realm", "cs2 wallhack", "cs2 radar hack", "csgo esp", "cs2 visual hack"]),
      metaKeywordsFa: JSON.stringify(["esp cs2", "شادو ریلم", "وال‌هک cs2", "هک رادار cs2"]),
      ogTitle: "Shadow Realm ESP — See Everything in CS2",
      ogDescription: "Skeleton glow, weapon identification, grenade trajectory prediction, and radar hack integration for CS2.",
      twitterTitle: "Shadow Realm ESP for CS2",
      twitterDescription: "Full visual enhancement with skeleton ESP and weapon identification for CS2.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g5_aim",
      name: "Apex Predator Core",
      slug: "apex-predator-core",
      game: "Apex Legends",
      category: "Aimbot",
      price: 32.99,
      priceDaily: 11.55,
      priceWeekly: 23.09,
      priceMonthly: 32.99,
      priceLifetime: 82.48,
      rating: 4.91,
      reviewsCount: 203,
      features: JSON.stringify(["Recoil elimination for all weapons", "Target prediction algorithm", "Silent aim with FOV limiter", "Stream-proof rendering"]),
      description: "Advanced aim assistance built for Apex's fast-paced movement. Features recoil elimination and target prediction for all weapon classes.",
      isPopular: true,
      bypassRate: "99.9%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/apex-predator-core.svg",
      bannerImage: "/images/products/apex-predator-core.svg",
      metaTitle: "Apex Predator Core — Apex Legends Aimbot",
      metaTitleFa: "هسته اکس پرداتور — ایم‌بات Apex Legends",
      metaDescription: "Advanced aim assistance for Apex Legends. Recoil elimination, target prediction, silent aim with FOV limiter. 99.9% undetected.",
      metaDescriptionFa: "کمک ایم پیشرفته برای Apex Legends. حذف ریکول، پیش‌بینی تارگت، ایم سکوت با محدودکننده FOV. ۹۹.۹٪ غیرقابل شناسایی.",
      focusKeyphrase: "apex legends aimbot",
      focusKeyphraseFa: "ایم‌بات apex legends",
      metaKeywords: JSON.stringify(["apex legends aimbot", "apex predator", "apex cheat", "apex hack", "best apex aimbot", "undetected apex"]),
      metaKeywordsFa: JSON.stringify(["ایم‌بات apex", "اکس پرداتور", "چیت apex", "هک apex legends"]),
      ogTitle: "Apex Predator Core — Dominate Apex Legends",
      ogDescription: "Recoil elimination and target prediction for all weapon classes in Apex Legends. Stream-proof rendering.",
      twitterTitle: "Apex Predator Core for Apex Legends",
      twitterDescription: "Advanced aim assistance built for Apex's fast-paced movement. Recoil elimination for all weapons.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g5_skin",
      name: "Royal Armory Skin Changer",
      slug: "royal-armory-skin-changer",
      game: "Apex Legends",
      category: "Skin Changer",
      price: 9.99,
      priceDaily: 3.50,
      priceWeekly: 6.99,
      priceMonthly: 9.99,
      priceLifetime: 24.98,
      rating: 4.65,
      reviewsCount: 74,
      features: JSON.stringify(["All legendary skins unlocked", "Weapon & character skin swap", "Client-side only rendering", "No server-side detection risk"]),
      description: "Unlock and equip any skin in the game without purchase. Client-side only, completely safe from detection.",
      isPopular: false,
      bypassRate: "100%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/royal-armory-skin-changer.svg",
      bannerImage: "/images/products/royal-armory-skin-changer.svg",
      metaTitle: "Royal Armory Skin Changer — All Apex Skins Unlocked",
      metaTitleFa: "تغییر پوسته رویال آرموری — همه پوسته‌های Apex باز شده",
      metaDescription: "Unlock all legendary skins in Apex Legends. Weapon & character skin swap, client-side only, zero detection risk.",
      metaDescriptionFa: "باز کردن همه پوسته‌های افسانه‌ای Apex Legends. تعویض پوسته سلاح و کاراکتر، فقط سمت کلاینت، ریسک شناسایی صفر.",
      focusKeyphrase: "apex legends skin changer",
      focusKeyphraseFa: "تغییر پوسته apex legends",
      metaKeywords: JSON.stringify(["apex skin changer", "royal armory", "apex legends skins", "apex cosmetic hack", "free apex skins"]),
      metaKeywordsFa: JSON.stringify(["تغییر پوسته apex", "رویال آرموری", "پوسته‌های apex", "آرایشی apex"]),
      ogTitle: "Royal Armory — Unlock All Apex Legends Skins",
      ogDescription: "Equip any skin in Apex Legends without purchase. Client-side only, completely safe from detection.",
      twitterTitle: "Royal Armory Skin Changer for Apex",
      twitterDescription: "Unlock all legendary skins in Apex Legends. Client-side only, zero detection risk.",
      schemaType: "SoftwareApplication",
    },
    {
      id: "g2_radar",
      name: "Siege Radar Hack",
      slug: "siege-radar-hack",
      game: "R6 Siege",
      category: "Radar",
      price: 12.99,
      priceDaily: 4.55,
      priceWeekly: 9.09,
      priceMonthly: 12.99,
      priceLifetime: 32.48,
      rating: 4.6,
      reviewsCount: 56,
      features: JSON.stringify(["Enemy position on minimap", "Gadget & trap detection", "Objective marker highlighting", "Drone camera integration"]),
      description: "Mini-map enhancement revealing enemy positions, gadget placements, and objective markers in real-time.",
      isPopular: false,
      bypassRate: "99.5%",
      updateStatus: "Undetected",
      imageUrl: "/images/products/siege-radar-hack.svg",
      metaTitle: "Siege Radar Hack — R6 Siege Minimap Enhancement",
      metaTitleFa: "هک رادار سایج — تقویت مینی‌مپ R6 Siege",
      metaDescription: "Real-time enemy positions on minimap for R6 Siege. Gadget detection, objective markers, drone camera integration. 99.5% undetected.",
      metaDescriptionFa: "موقعیت دشمن بلادرنگ روی مینی‌مپ R6 Siege. شناسایی گجت، نشانگر اهداف، یکپارچگی دوربین پهپاد. ۹۹.۵٪ غیرقابل شناسایی.",
      focusKeyphrase: "r6 siege radar hack",
      focusKeyphraseFa: "هک رادار r6 siege",
      metaKeywords: JSON.stringify(["r6 radar hack", "siege minimap hack", "r6 siege cheat", "rainbow six radar", "r6s minimap"]),
      metaKeywordsFa: JSON.stringify(["هک رادار r6", "هک مینی‌مپ siege", "چیت rainbow six"]),
      ogTitle: "Siege Radar Hack — Enemy Positions on Minimap",
      ogDescription: "Reveal enemy positions, gadget placements, and objective markers on your minimap in real-time.",
      twitterTitle: "Siege Radar Hack for R6 Siege",
      twitterDescription: "Real-time enemy positions and gadget detection on your minimap for R6 Siege.",
      schemaType: "SoftwareApplication",
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  // Seed promo codes
  await prisma.promoCode.create({
    data: {
      code: "WELCOME50",
      discount: 50,
      discountType: "percent",
      maxUses: 100,
      active: true,
    },
  });

  await prisma.promoCode.create({
    data: {
      code: "GOLD100",
      discount: 100,
      discountType: "fixed",
      maxUses: 50,
      active: true,
    },
  });

  // Seed reviews — link to existing users and products
  const allProducts = await prisma.product.findMany({ select: { id: true } });
  const demoUser = await prisma.user.findUnique({ where: { username: "demo_user" } });
  const adminUser = await prisma.user.findUnique({ where: { username: "admin" } });

  if (allProducts.length >= 3 && demoUser && adminUser) {
    const reviewData = [
      { productId: allProducts[0].id, userId: demoUser.id, rating: 5, comment: "Best aimbot I've ever used. Completely undetected after 3 months of daily play. Worth every penny!" },
      { productId: allProducts[0].id, userId: adminUser.id, rating: 4, comment: "Solid performance, good bypass rate. Minor suggestion: add more FOV presets." },
      { productId: allProducts[1].id, userId: demoUser.id, rating: 5, comment: "Wallhack works flawlessly. I can see every enemy through walls. Game-changing." },
      { productId: allProducts[2].id, userId: adminUser.id, rating: 4, comment: "Great ESP overlay. Customizable and clean UI. Highly recommended for competitive play." },
    ];

    for (const r of reviewData) {
      await prisma.review.create({ data: r });
    }

    // Update product ratings
    for (const p of allProducts.slice(0, 3)) {
      const agg = await prisma.review.aggregate({
        where: { productId: p.id },
        _avg: { rating: true },
        _count: { rating: true },
      });
      await prisma.product.update({
        where: { id: p.id },
        data: {
          rating: Math.round((agg._avg.rating || 0) * 10) / 10,
          reviewsCount: agg._count.rating,
        },
      });
    }
  }

  console.log("✅ Database seeded successfully!");
  console.log("   Admin: username=admin, password=admin123");
  console.log("   User:  username=demo_user, phone=09375302400, password=user123");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
